### ISSUE TITLE
Quality control against Let's Play WoW Draenei Shaman 1 - 80 [video 1/142]

### ISSUE THREAD

**Issue by Phatcat** [unified-db/Database#251]
https://www.youtube.com/watch?v=aJWK6sSWWno&list=PL28173C4849CA7E04&index=1
(Set to 0.25 speed)

2:12
~~Firmanvaar should not do /talk animation when you initially interact with him
Also he should do /talk animation when you select the quest from the menu, currently he doesn't.~~

2:28
the client bugs out, not updating the quest window to the next quest, making you stuck as the window now becomes totally unresponsive to pressing complete quest or cancel, so you have to close it by [x].

2:34
Zaldunn should once in a while stop and heal one of the injured Draenei, like we see in the video

2:42
Proenitus should do /talk animation when you select the quest from his gossip menu

2:52
Vindicator Aldar has his gossip menu but he is missing his quest "Inoculation" (EntryID 9303)

3:37
No Draenei Survivors here to heal on cmangos - Are these positions pooled? if not it's missing, if so... it may still be missing ^^

3:54
Botanist Taerix is supposed to do an animatoin when you accept the quest, currently doesn't.

5:52
It should automatically ask you about the next quest she has in line, while on cmangos contact is ended and you have to re-initiate contact with her

6:48
When Inoculation Crystal is used on Nestlewood Owlkin it should move around confused for a bit before despawning and not just stand still before despawning.
~~These owlkin unlike the others seem to also have been neutral back then as well~~ probably came with patch 3.3.0

8:09
Turning in this quest should lead you into the gossip menu for his next quest, currently it closes the window so you have to re-enact with him.

8:20
she displays the wrong gossip text on cmangos in this context (on cmangos she says "How are we ever going to get out of here?" - is only 1 word too many to fit on one line)
in the video the text can barely fit the 2 lines. It's hard to make out what exactly she is saying, though.

8:46
There should be some more mobs; there should at least be a lot more fighting going on (it doesn't quite feel as hectic or alive on cmangos as it looks in the video) - more like 6 or 7 of the earth elementals (counted 4, maybe 5 on cmangos) and 3 - 4 of each of the other and respawning somewhat faster than that on cmangos.
Edit*: It can very much be the fact that 'the event' was just getting started / settling in when I showed up and on an active server it would perhaps feel more like in the vid... This one I am really not sure about..

9:29
Firmanvaar is supposed to do /shrug animation not /talk animation when you select 'Call of Earth' from the gossip menu
Also when you complete the quest and he teaches you the spell, he should cast it onto you, like trainers normally do, currently he doesn't.

---

Patch 3.3.0 differences to video (recorded pre 3.3.0)

~~0:13
The shaman class is not supposed to spawn with a shield. (5:02 is where we see the shaman in the video first pick up a shield)~~

~~0:59
Quest gossip menu is not supposed to show any rewards if the only reward is exp; it should not tell you how much exp a quest gives at all.~~

~~1:28
The player should spawn with 5 of those bread things and 5 refreshing spring water; currently the player doesn't start with any of that.~~

~~4:16
All these mobs here should not be 'neutral' but rather hostile... this probably goes for a lot of mobs in all the level 1 - 6 areas.. or was this done during wrath?~~

~~9:58
Blood elves along with a lot of other mobs here and in 1 - 6 zones should probably be hostile as shown in the vid (unless that was changed pre-cata)~~

**Comment by offl** [comment]
>0:13
The shaman class is not supposed to spawn with a shield. (5:02 is where we see the shaman in the video first pick up a shield)

Changed in 3.3.0, [link](http://wow.gamepedia.com/Patch_3.3.0).
Default Equipment: Starting weapons are now more uniform. Rogues now start with a pair of daggers equipped. All other classes except shamans start with a 2-handed weapon equipped and the required skill already known. **Shamans start with a 1-handed weapon and a shield**, as they benefit more from the shield than they would from a 2-handed weapon.

>1:28
The player should spawn with 5 of those bread things and 5 refreshing spring water; currently the player doesn't start with any of that.

[Level 1 characters no longer start with food or water in their inventory.](http://wow.gamepedia.com/Patch_3.3.0)

>4:16
All these mobs here should not be 'neutral' but rather hostile... this probably goes for a lot of mobs in all the level 1 - 6 areas.. or was this done during wrath?

Guess this too was changed in 3.3.0.

>9:58
Blood elves along with a lot of other mobs here and in 1 - 6 zones should probably be hostile as shown in the vid (unless that was changed pre-cata)

Changed in 3.3.0 ([WH1](http://www.wowhead.com/npc=16521/blood-elf-scout#comments:id=960199), [WH2](http://www.wowhead.com/npc=16521/blood-elf-scout#comments:id=935963)).

The video was recorded before 3.3.0.

**Comment by Phatcat** [comment]
Sounds like 3.3.0 really was a fun patch overall, huh? easy-moding everything into the ground...

Yeah, I did notice a few client differences which got me thinking that some of that stuff may be do to patch differences. Thanks for digging them out for me. These probably won't be the last patch differences I may make note of..

I will ammend the issue accordingly, read up on the dreaded 3.3.0 and try to take it into account as much as possible in the later vids..

**Comment by offl** [comment]
>3:37
No Draenei Survivors here to heal on cmangos - Are these positions pooled? if not it's missing, if so... it may still be missing ^^
also should they even glow like red like they do on cmangos? I don't see any of that glow in the video
Also when they get up they are supposed to say something, then stop being dazed/confused (pay attention during 3:41), and then run away
Currently says nothing, stays confused/dazed and walks away.

On retail they are pooled(40 spawns, if I remember correctly).
Guess the script is completely incorrect, each of them also should use different paths after healing.

>4:03
Items are presented in wrong order, it should go chests -> leggings -> belts -> boots -> wrists -> gloves -> shields

For this needed new column called "slot". But how to order items correctly today(for all NPCs)?
In another project this column exists, but unused for TBC NPCs. So currently  items are ordered by ID.

Similar NPC and his slots. Third column - slot.
```
(1213, 2379, 1, 0, 0, 1), -- Tarnished Chain Vest
(1213, 2381, 2, 0, 0, 1), -- Tarnished Chain Leggings
(1213, 2380, 3, 0, 0, 1), -- Tarnished Chain Belt
(1213, 2383, 4, 0, 0, 1), -- Tarnished Chain Boots
(1213, 2384, 5, 0, 0, 1), -- Tarnished Chain Bracers
(1213, 2385, 6, 0, 0, 1), -- Tarnished Chain Gloves
(1213, 17184, 7, 0, 0, 1), -- Small Shield
(1213, 2129, 8, 0, 0, 1), -- Large Round Shield
```
--

Also multiple changes to quest system was added in 3.3.0. Maybe some of your bugs related to quest system are not bugs. Don't know.

**Comment by Phatcat** [comment]
the thing about quests displaying the amount of exp they give may very well have been added in 3.3.0, but the missing/wrong animations as well as the one missing quest, those are not patch differences (unless they decided to remove that one quest, which I find highly unlikely)

**Comment by Phatcat** [comment]
I'm thinking there must be a natural order to this that blizzard just went and used for all of these (or a couple of sets to switch between), and I'm guessing it's ordered by item slot/type (where it fits on your char / what kind of thing it is) and then subsorted by level.

**Comment by offl** [comment]
Quite possible :)

**Comment by Grz3s** [comment]
```quote
0:59
 Quest gossip menu is not supposed to show any rewards if the only reward is exp; it should not tell you how much exp a quest gives at all.
```
https://www.youtube.com/watch?v=u54k_E4EXyU&list=PL029F64058F6E97A3&index=1
check 0:50  ... and any other quest after ...
Release date of this avi is 06.04.2010 ... so I would place it when patch 3.3.3a was released
http://wowwiki.wikia.com/wiki/Patches/3.x

It may be an issue for TBC or Vanilla but not here ;).... can be crossed off.

**Comment by Phatcat** [comment]
@offl I was following the video, doing all quests in the exact same order at the exact same time; I should be getting the same gossip menus. I didn't.

**Comment by Phatcat** [comment]
actually 3.3.5 released a bit later that month http://us.battle.net/wow/en/game/patch-notes/3-3-5, so it's only 3.3.3, but it's still post 3.3.0 which is probably the important bit since that's the big client patch that changed and nerfed a lot of things.

**Comment by Phatcat** [comment]
> first part comes from npc_text -- this is WDB data ... (smth may be changed after 3.3.3 release there - but this wont be changed)

If I find a video from 3.3.5a that shows the same as the lets play video, would you correct it then? Because I think it's indeed not correct on cmangos (I don't believe they removed any animations from gossip, give me one single good reason they would (it makes their game feel more dead - they added it originally to make it feel more alive surely))

**Comment by offl** [comment]
>@offl I was following the video, doing all quests in the exact same order at the exact same time; I should be getting the same gossip menus. I didn't.

Because it's not implemented. Currently she displays the correct text, but another one should be displayed when player turn in the quest - not implemented.

**Comment by Grz3s** [comment]
```quote
2:28
 the client bugs out, not updating the quest window to the next quest, making you stuck as the window now becomes totally unresponsive to pressing complete quest or cancel, so you have to close it by [x].
```
-- fixed*

* - will add all in one fix-file

**Comment by Grz3s** [comment]
@Phatcat  regarding to that : 
2:12
 Firmanvaar should not do /talk animation when you initially interact with him
 Also, the quest to turn in 'Shaman Training' has a blue question mark in the gossip menu while it should be yellow.
 Also he should do /talk animation when you select the quest from the menu, currently he doesn't.

pls look at this vid:.
https://youtu.be/q0M3MHP2sgA

**Comment by Grz3s** [comment]
```qoute
2:34
 Zaldunn should once in a while stop op and heal one of the injured Draenei, like we see in the video
```
-- fixed*

**Comment by JaredNinja** [comment]
I've been playing draenei with a couple of friends yesterday. 2 things seemed off:

Quest "Help Tavara" broken? NPC had full health and no heal would trigger the expected outcome

Quest "Saving Princess Stillpine" should spawn "High Chief Bristlelimb" at some point. It doesn't unfortunately.

[installed from scratch the latest cmangos wotlk, udb and client 3.3.5a - 3 days ago]

**Comment by Grz3s** [comment]
@JaredNinja  .. make sure you have latest ACID added into mangos database (its an very important part of this DB)
https://github.com/ACID-Scripts/WOTLK/commits/master

**Comment by JaredNinja** [comment]
@Grz3s

First of all, thank you for replying. I really appreciate your time and work.

What I did was; I followed the guide at https://github.com/cmangos/issues/wiki/Installation-Instructions

It states the ACID part is optional on several occasions. I believe I tried the first time, and got a SQL error. So then I wiped the 3 databases and did a clean import of just the UDB stuff. I still have the ACID folder as the instructions told me, but I believe it serves no purpose at the moment for my setup.

I will give ACID another go now that you explained me it does have a major purpose.

Could I contact you for a few other questions about this cmangos wotlk server I run in the last 3 days? I would love to help in this project because I'm an old WoW player and professional developer. My questions are simply about how recent cores and databases are, which to pick and how to help improve these.

**Comment by JaredNinja** [comment]
Update: ACID did not solve it unfortunately.

Also, the starting items of characters have questionmarks as icons. The hunter crossbow is not recognized as a proper ranged weapon either. Simply create a lvl 1 hunter (I tried draenei) to reproduce. The first set of (questionmark icon) gear is not immediately visible to other players either. The class/race combinations are not enforced correctly either.

There seems to be a handful of work for me to fix on my server :-)

**Comment by Grz3s** [comment]
@Phatcat 
```quote
3:37
 No Draenei Survivors here to heal on cmangos - Are these positions pooled? if not it's missing, if so... it may still be missing ^^
 also should they even glow like red like they do on cmangos? I don't see any of that glow in the video (could be patch difference)
 Also when they get up they are supposed to say something, then stop being dazed/confused (pay attention during 3:41), and then run away
 Currently says nothing, stays confused/dazed and walks away.
```
I added missing ones...
Quest is scripted by Sd2 script in azuremyst_isle.cpp
- UDB has 18 spawns for them -- so not many were missing..
- they have aura - 35046  (red glow) - this is correct
- after spell hit... they will stand up .. say text and cast spell 28630 on themselves (confused) - this is also correct (not removed as you say)

Only missing part is that they should run (currently moving) - @xfurry  can you pls update it?

**Comment by Phatcat** [comment]
> after spell hit... they will stand up .. say text and cast spell 28630 on themselves (confused) - this is also correct (not removed as you say)

https://youtu.be/aJWK6sSWWno?t=3m37s - watch it at 0.25
she is confused before she even gets up, and she stays confused as she talks, but she stops being confused right before she runs away... this is not something I am saying, this is something a video is undeniably showing...

> She does all emotes ... on gossip + emotes on quest taken

Well, if if has an animation implemented and it works I may just have missed it while playing, in that case sorry, I do try to double check everything before making a note.

**Comment by Phatcat** [comment]
but I will move that point over and post it it on the core instead since it's done with SD2 (I wasn't sure if it was a db script, acid or sd2, we have so many different ways of doing special mob behaviour =))

**Comment by Grz3s** [comment]
spell 28630 is casted straight after player casts "gift of naaru"
```code
ServerToClient: SMSG_AURA_UPDATE (0x65C0) Length: 16 ConnIdx: 0 Time: 02/10/2011
GUID: Full: 0xF1304063000D4E9C Type: Creature c
[0] Slot: 0
[0] Spell ID: 28630 (28630)
[0] Flags: EffectIndex0, NotCaster, Positive (25)
[0] Level: 2
[0] Charges: 0

ServerToClient: SMSG_SPELL_START (0x6BA8) Number: 15410
Caster GUID: Full: 0xF1304063000D4E9C Type: Creature c
Caster Unit GUID: Full: 0xF1304063000D4E9C Type: Creature c
Cast Count: 0
Spell ID: 28630 (28630)
Cast Flags: HasTrajectory (2)
Time: 0
Target Flags: Self (0)

ServerToClient: SMSG_SPELL_GO (0x30C0) Number: 15411
Caster GUID: Full: 0xF1304063000D4E9C Type: Creature c
Caster Unit GUID: Full: 0xF1304063000D4E9C Type: Creature c
Cast Count: 0
Spell ID: 28630 (28630)
Cast Flags: Unknown7 (256)
Time: 222361133
Hit Count: 1
[0] Hit GUID: Full: 0xF1304063000D4E9C Type: Creature c
Miss Count: 0
Target Flags: Unit (2)
Target GUID: 0x0
```

It may be removed when she starts running...  but as I said before .. 
Its a SD2 script... (sd2 scripts are fixed directly in core - UDB has nothing to do with them) .. you can correct it if you can :)

**Comment by Phatcat** [comment]
I know, I know, I'm sorry for posting it here, I didn't know what was handling it, I'm reopening the issue for the core again - thanks for looking into the data ^^

**Comment by Phatcat** [comment]
so this cast flag unk7 can very well have something to do with casting while lying down?

**Comment by Grz3s** [comment]
```quote

4:03
 Items are presented in wrong order, it should go chests -> leggings -> belts -> boots -> wrists -> gloves -> shields

For this needed new column called "slot". But how to order items correctly today(for all NPCs)?
 In another project this column exists, but unused for TBC NPCs. So currently items are ordered by ID.

Similar NPC and his slots. Third column - slot. The only way to fix it is using data from retail or another DB. Don't know how fix this today for classic NPCs(from Orgrimmar, for example) - they too are bugged, ofc.
(1213, 2379, 1, 0, 0, 1), -- Tarnished Chain Vest
(1213, 2381, 2, 0, 0, 1), -- Tarnished Chain Leggings
(1213, 2380, 3, 0, 0, 1), -- Tarnished Chain Belt
(1213, 2383, 4, 0, 0, 1), -- Tarnished Chain Boots
(1213, 2384, 5, 0, 0, 1), -- Tarnished Chain Bracers
(1213, 2385, 6, 0, 0, 1), -- Tarnished Chain Gloves
(1213, 17184, 7, 0, 0, 1), -- Small Shield
(1213, 2129, 8, 0, 0, 1), -- Large Round Shield
```

Yes this is a core issue.... no  diff what order we'll set up these items on list they still will be set randomly?  Column with slots  would solve this issue//

**Comment by Phatcat** [comment]
I don't believe they are set randomly, no, but I will move it to the core issue since this is not handled db site, once again, sorry ^^

**Comment by Grz3s** [comment]
(...)
These owlkin unlike the others seem to also have been neutral back then as well probably came with patch 3.3.0

```quote
By Helgz (1,375 – 6·12)  on 2010/02/18 (Patch 3.3.2)   
These are no longer hostile.
```

**Comment by Phatcat** [comment]
Oh, it wasn't written very well, I was actually talking about the OTHER owlkin, the ones we see being hostile in the video, it's those I refer to probably also changing to neutral in 3.3.0 - it looks like these owlkin for the quest have always been neutral.

**Comment by Grz3s** [comment]
```quote
6:48
 When Inoculation Crystal is used on Nestlewood Owlkin it should move around confused for a bit before despawning and not just stand still before despawning.
```
Core issue... Somehow:
spell_scripts.cpp
```code
pCreatureTarget->UpdateEntry(NPC_OWLKIN_INOC);
```
If i'm understanding this correctly ... this after creature killed/despawned should go back to default
Respawned creature should go back to his original entry/model/name etc..
Only problem is that... his EventAI... stays from that updated creature:) (smth missing in code?)
So we have funny situation where... 
Creature X .. is using creatures Y EventAI.... :/ (and this brakes everything)

**Comment by Grz3s** [comment]
I should close this issue - all DB problems were fixed.
We have few issues core/ScriptDev2 side:

- "?" in quest details not fixed for special quests. (should be "!")  -- core issue
-  q.9283 - scripted in Sd2 .. they should "run" not "walk"  -- ScriptDev2 issue
- items in vendors list are placed in wrong order  - core issue
- core "UpdateEntry" for some sd2 scripts . is partly broken ...  -- Core/ScriptDev2 issue

More details about all of issues can be found above ....

**Comment by Grz3s** [comment]
I should close this issue - all DB problems were fixed.
We have few issues core/ScriptDev2 side:

- "?" in quest details not fixed for special quests. (should be "!")  -- core issue
-  q.9283 - scripted in Sd2 .. they should "run" not "walk"  -- ScriptDev2 issue
- items in vendors list are placed in wrong order  - core issue
- core "UpdateEntry" for some sd2 scripts . is partly broken ...  -- Core/ScriptDev2 issue

More details about all of issues can be found above ....

**Comment by Grz3s** [comment]
its closed only for DB...
Core issues are still need to be looked at

**Comment by Phatcat** [comment]
Sure do. I have updated the core issue accordingly, you may want to make additional notes if I forgot something. Thank you =)
